include minimal

package macos required formula fzf
package macos required formula zoxide
package macos optional formula eza
package macos optional formula bat
package macos required formula pyenv
package macos required formula nvm
package macos required formula vim
package macos required direct zinit
package macos required direct vundle

package ubuntu required apt fzf
package ubuntu required apt zoxide
package ubuntu optional apt eza
package ubuntu optional apt bat
package ubuntu required apt vim
package ubuntu required apt unzip
package ubuntu required apt build-essential
package ubuntu required apt libssl-dev
package ubuntu required apt zlib1g-dev
package ubuntu required apt libbz2-dev
package ubuntu required apt libreadline-dev
package ubuntu required apt libsqlite3-dev
package ubuntu required apt libncursesw5-dev
package ubuntu required apt xz-utils
package ubuntu required apt tk-dev
package ubuntu required apt libxml2-dev
package ubuntu required apt libxmlsec1-dev
package ubuntu required apt libffi-dev
package ubuntu required apt liblzma-dev
package ubuntu required direct pyenv
package ubuntu required direct nvm
package ubuntu required direct zinit
package ubuntu required direct vundle
