include minimal

package all required direct mise
package all required mise fzf
package all required mise zoxide
package all required mise ripgrep
package all optional mise eza
package all optional mise bat
package all required mise jq
package all required mise neovim
package all required mise tree-sitter
package all required mise node
package all required mise python
package all required mise uv
package all required mise gh

package ubuntu required apt build-essential
