include minimal

package macos required formula pyenv
package macos required formula pyenv-virtualenv
package macos required formula nvm
package macos required formula kubectl
package macos optional formula kubectx
package macos optional formula openjdk@17

package ubuntu required apt unzip
package ubuntu required apt build-essential
package ubuntu required apt libssl-dev
package ubuntu required apt zlib1g-dev
package ubuntu required apt libbz2-dev
package ubuntu required apt libreadline-dev
package ubuntu required apt libsqlite3-dev
package ubuntu required apt libncursesw5-dev
package ubuntu required apt xz-utils
package ubuntu required apt tk-dev
package ubuntu required apt libxml2-dev
package ubuntu required apt libxmlsec1-dev
package ubuntu required apt libffi-dev
package ubuntu required apt liblzma-dev
package ubuntu required direct pyenv
package ubuntu required direct pyenv-virtualenv
package ubuntu required direct nvm
package ubuntu required direct kubectl
package ubuntu optional apt kubectx
package ubuntu optional apt openjdk-17-jdk
