include kubernetes

package macos optional formula openjdk@17
package macos optional cask ghostty
package macos optional cask font-meslo-lg-nerd-font
package macos optional cask font-noto-sans-cjk-kr
