# platform  requirement  manager  package
package macos required formula git
package macos required formula starship
package ubuntu required apt zsh
package ubuntu required apt git
package ubuntu required apt curl
package ubuntu required apt ca-certificates
package ubuntu required direct starship
