# kubectl aliases compatible with the Oh My Zsh kubectl plugin. Completion is
# configured separately in common.zsh so these aliases have zero startup cost.

if (( $+commands[kubectl] )); then
  alias k='kubectl'
  alias kd='kubectl describe'
  alias kg='kubectl get'
  alias kaf='kubectl apply -f'
  alias kapk='kubectl apply -k'
  alias keti='kubectl exec -t -i'
  alias kcuc='kubectl config use-context'
  alias kcsc='kubectl config set-context'
  alias kccc='kubectl config current-context'
  alias kcgc='kubectl config get-contexts'
  alias kdel='kubectl delete'
  alias kdelf='kubectl delete -f'
  alias kge='kubectl get events --sort-by=.lastTimestamp'
  alias kgp='kubectl get pods'
  alias kgpa='kubectl get pods --all-namespaces'
  alias kgpw='kubectl get pods --watch'
  alias kgpwide='kubectl get pods -o wide'
  alias kep='kubectl edit pods'
  alias kdp='kubectl describe pods'
  alias kdelp='kubectl delete pods'
  alias kgs='kubectl get svc'
  alias kgsa='kubectl get svc --all-namespaces'
  alias kes='kubectl edit svc'
  alias kds='kubectl describe svc'
  alias kdels='kubectl delete svc'
  alias kgi='kubectl get ingress'
  alias kgia='kubectl get ingress --all-namespaces'
  alias kei='kubectl edit ingress'
  alias kdi='kubectl describe ingress'
  alias kdeli='kubectl delete ingress'
  alias kgns='kubectl get namespaces'
  alias kcn='kubectl config set-context --current --namespace'
  alias kgcm='kubectl get configmaps'
  alias kgsec='kubectl get secret'
  alias kgd='kubectl get deployment'
  alias kgda='kubectl get deployment --all-namespaces'
  alias ked='kubectl edit deployment'
  alias kdd='kubectl describe deployment'
  alias kdeld='kubectl delete deployment'
  alias ksd='kubectl scale deployment'
  alias krsd='kubectl rollout status deployment'
  alias krrd='kubectl rollout restart deployment'
  alias kgss='kubectl get statefulset'
  alias kess='kubectl edit statefulset'
  alias kdss='kubectl describe statefulset'
  alias kdelss='kubectl delete statefulset'
  alias kpf='kubectl port-forward'
  alias kga='kubectl get all'
  alias kgaa='kubectl get all --all-namespaces'
  alias kl='kubectl logs'
  alias klf='kubectl logs -f'
  alias kcp='kubectl cp'
  alias kgno='kubectl get nodes'
  alias kdno='kubectl describe node'
  alias kgpvc='kubectl get pvc'
  alias kdpvc='kubectl describe pvc'
  alias kgds='kubectl get daemonset'
  alias kgcj='kubectl get cronjob'
  alias kgj='kubectl get job'
fi

if (( $+commands[kubectx] )); then
  alias kx='kubectx'
fi

if (( $+commands[kubens] )); then
  alias kn='kubens'
fi
