# Git aliases kept compatible with the commonly used Oh My Zsh git aliases.
# Git completion itself is provided by Zsh's built-in _git function.

alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gapa='git add --patch'
alias gb='git branch'
alias gbd='git branch --delete'
alias gc='git commit --verbose'
alias 'gc!'='git commit --verbose --amend'
alias gcmsg='git commit --message'
alias gd='git diff'
alias gds='git diff --staged'
alias gf='git fetch'
alias gl='git pull'
alias gpr='git pull --rebase'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase --interactive'
alias grs='git restore'
alias grst='git restore --staged'
alias gst='git status'
alias gsb='git status --short --branch'
alias gsta='git stash push'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gsw='git switch'
alias gswc='git switch --create'
alias glo='git log --oneline --decorate'
alias glog='git log --oneline --decorate --graph'
alias gwt='git worktree'
alias gwta='git worktree add'
alias gwtls='git worktree list'
alias gwtrm='git worktree remove'
