# --------------------------------------------------
# Runtime environments
# Define load_nvm in each OS-specific .zshrc before loading this file
# --------------------------------------------------

export NVM_DIR="$HOME/.nvm"

nvm()  { load_nvm; nvm "$@" }
node() { load_nvm; command node "$@" }
npm()  { load_nvm; command npm "$@" }
npx()  { load_nvm; command npx "$@" }


# Pyenv
export PYENV_ROOT="$HOME/.pyenv"

if [[ -d "$PYENV_ROOT/bin" ]]; then
  export PATH="$PYENV_ROOT/bin:$PATH"
fi

if command -v pyenv >/dev/null 2>&1; then
  eval "$(pyenv init - zsh)"
fi


# --------------------------------------------------
# Zinit
# --------------------------------------------------

ZINIT_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git"

if [[ -s "$ZINIT_HOME/zinit.zsh" ]]; then
  source "$ZINIT_HOME/zinit.zsh"

  # Additional completion definitions
  # Reinstall completion files when the plugin is updated
  zinit ice blockf atpull'zinit creinstall -q .'
  zinit light zsh-users/zsh-completions

  # Load selected Oh My Zsh plugins through Zinit
  zinit for \
    OMZL::git.zsh \
    OMZP::git \
    OMZP::kubectl

  # Complete by prefix, case-insensitive match, then substring match
  zstyle ':completion:*' matcher-list \
    '' \
    'm:{a-zA-Z}={A-Za-z}' \
    'l:|=* r:|=*'

  # Initialize completion directly because Oh My Zsh is not loaded
  autoload -Uz compinit
  ZCOMPDUMP="${ZDOTDIR:-$HOME}/.zcompdump"

  if [[ -n "$ZCOMPDUMP"(#qN.mh+24) ]]; then
    compinit -d "$ZCOMPDUMP"
  else
    compinit -C -d "$ZCOMPDUMP"
  fi

  # Apply compdef calls deferred while plugins were loading
  zinit cdreplay -q

  # Explicitly register the completion generated by the kubectl plugin
  if (( $+commands[kubectl] )); then
    autoload -Uz _kubectl
    compdef _kubectl kubectl
    compdef _kubectl k
  fi

  # Run aws_completer only when completion is requested
  if (( $+commands[aws] && $+commands[aws_completer] )); then
    autoload -Uz bashcompinit
    bashcompinit
    complete -C aws_completer aws
  fi

  # Zinit command completion
  autoload -Uz _zinit
  compdef _zinit zinit
else
  print -u2 "Zinit not found: $ZINIT_HOME"
fi


# --------------------------------------------------
# Aliases
# --------------------------------------------------

if command -v kubectl >/dev/null 2>&1; then
  alias k='kubectl'
  alias kd='kubectl describe'
  alias kg='kubectl get'
fi

if command -v kubectx >/dev/null 2>&1; then
  alias kx='kubectx'
fi

if command -v kubens >/dev/null 2>&1; then
  alias kn='kubens'
fi

if command -v bat >/dev/null 2>&1; then
  alias cat='bat'
elif command -v batcat >/dev/null 2>&1; then
  alias cat='batcat'
fi

if command -v eza >/dev/null 2>&1; then
  alias ls='eza --icons=auto'
fi


# --------------------------------------------------
# Shell tools
# --------------------------------------------------

if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi

if command -v fzf >/dev/null 2>&1; then
  if FZF_ZSH_INIT="$(fzf --zsh 2>/dev/null)"; then
    eval "$FZF_ZSH_INIT"
  elif [[ -r /usr/share/doc/fzf/examples/key-bindings.zsh ]]; then
    source /usr/share/doc/fzf/examples/key-bindings.zsh
  fi
  unset FZF_ZSH_INIT
fi


# --------------------------------------------------
# Interactive plugins
# Initialize after tools that configure key bindings
# --------------------------------------------------

if (( $+functions[zinit] )); then
  zinit light zsh-users/zsh-autosuggestions

  # Load syntax highlighting as late as possible
  zinit light zdharma-continuum/fast-syntax-highlighting
fi


# --------------------------------------------------
# Prompt
# Initialize Starship after the other prompt-related settings
# --------------------------------------------------

if command -v starship >/dev/null 2>&1; then
  eval "$(starship init zsh)"
fi
