set nocompatible
filetype plugin indent on

if has("syntax")
	syntax enable
endif

set nu
set rnu
set hlsearch
set autoindent
set cindent
set ts=2
set sts=2
set shiftwidth=2
set expandtab
set laststatus=2
set signcolumn=yes
set cursorline
set ignorecase
set smartcase
set smarttab
set smartindent
set ruler
set fileencodings=utf8,euc-kr
set completeopt=menu,menuone,noselect
set wmnu

if has("mouse")
	set mouse=a
endif

if has("clipboard")
	set clipboard=unnamedplus
endif

" inoremap " ""<left>
" inoremap ' ''<left>
" inoremap ( ()<left>
" inoremap [ []<left>
" inoremap { {}<left>
" inoremap {<CR> {<CR>}<ESC>O
" inoremap {;<CR> {<CR>};<ESC>O

au BufReadPost *
\ if line("'\"") > 0 && line("'\"") <= line("$") |
\ exe "norm g`\"" |
\ endif
