filetype plugin indent on

if has("syntax")
	syntax enable
endif

set nu
set rnu
set hlsearch
set autoindent
set cindent
set ts=2
set sts=2
set shiftwidth=2
set expandtab
set laststatus=2
set signcolumn=yes
set cursorline
set ignorecase
set smartcase
set smarttab
set smartindent
set ruler
set fileencodings=ucs-bom,utf8,euc-kr
set completeopt=menu,menuone,noselect
set wmnu

if has("mouse")
	set mouse=a
endif

if has("clipboard")
	set clipboard=unnamedplus
endif

" Skip commit and rebase messages, xxd dumps, and diff mode (:h last-position-jump).
augroup SelfishellRestoreCursor
  autocmd!
  autocmd BufReadPost *
        \ if line("'\"") >= 1 && line("'\"") <= line("$") && &filetype !~# 'commit'
        \   && index(['xxd', 'gitrebase'], &filetype) == -1 && !&diff |
        \   execute "normal! g`\"" |
        \ endif
augroup END
